name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.5.4
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: ^3.1.0

dependencies:
  json_annotation: ^4.8.1
  # http: ^0.13.5
  http: ^1.2.1

dev_dependencies:
  test: ^1.24.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
